
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri May 28 12:35:07 CEST 2021
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int EXPBIS = 30;
  public static final int MASMAS = 31;
  public static final int DOSPUNTOS = 3;
  public static final int DIVBIS = 28;
  public static final int MENOSMENOS = 32;
  public static final int CHAR = 40;
  public static final int POR = 26;
  public static final int NOTIGUALLOG = 16;
  public static final int CCIERRE = 9;
  public static final int PCIERRE = 7;
  public static final int LCIERRE = 11;
  public static final int LAP = 10;
  public static final int USING = 45;
  public static final int CASE = 56;
  public static final int CONTINUE = 52;
  public static final int CAP = 8;
  public static final int INT = 37;
  public static final int PUNTOCOMA = 2;
  public static final int FOR = 49;
  public static final int MINUS = 24;
  public static final int NUMENT = 61;
  public static final int NOT = 15;
  public static final int MENORIGUAL = 18;
  public static final int AND = 13;
  public static final int IGUAL = 5;
  public static final int CARACTER = 60;
  public static final int OR = 14;
  public static final int BOOL = 39;
  public static final int CLASS = 36;
  public static final int DIV = 27;
  public static final int IF = 46;
  public static final int EXP = 29;
  public static final int MAYORIGUAL = 20;
  public static final int EOF = 0;
  public static final int RETURN = 35;
  public static final int DIRMEM = 33;
  public static final int TRUE = 42;
  public static final int NEW = 54;
  public static final int error = 1;
  public static final int INCLUDE = 58;
  public static final int COMA = 4;
  public static final int MENOR = 17;
  public static final int PRUNT = 51;
  public static final int MOD = 21;
  public static final int BREAK = 53;
  public static final int VOID = 41;
  public static final int NUMREAL = 62;
  public static final int SWITCH = 55;
  public static final int PUNT = 34;
  public static final int MAYOR = 19;
  public static final int PAP = 6;
  public static final int MODBIS = 22;
  public static final int ELSE = 47;
  public static final int ENUM = 44;
  public static final int IDEN = 63;
  public static final int WHILE = 48;
  public static final int DEFAULT = 57;
  public static final int FLOAT = 38;
  public static final int IGUALLOG = 12;
  public static final int STRING = 59;
  public static final int FALSE = 43;
  public static final int MINUSBIS = 25;
  public static final int PRINT = 50;
  public static final int MAS = 23;
}

