package ast;

public enum TipoE {
SUMA,RESTA,NEW, MUL,DIV,MOD,POW,OPUESTO,AND,OR,NOT,IGUALLOG,NOTIGUAL,MENOR,MENORIGUAL,MAYOR,MAYORIGUAL,NUM,BOOL,CHAR,IDEN,MASMAS,MENOSMENOS,DIRMEM,DEREF,INSTANCE,SUBINDICE,FUNCTION,LIST
}
